### ISSUE TITLE
Missing template perfdashboard/contexts/bullet

### ISSUE THREAD

**Issue by jirutka** [ezrondre/perfdashboard#4]
```
Started GET "/?context=bullet" for ::1 at 2015-06-14 23:03:57 +0200
Processing by Perfdashboard::RequestsController#index as HTML
  Parameters: {"context"=>"bullet"}
  Perfdashboard::Server Load (0.3ms)  SELECT  `perfdashboard_servers`.* FROM `perfdashboard_servers` WHERE `perfdashboard_servers`.`id` IS NULL LIMIT 1
   (0.4ms)  SELECT DISTINCT `perfdashboard_contexts`.`name` FROM `perfdashboard_contexts`
Completed 500 Internal Server Error in 6ms (ActiveRecord: 0.6ms)

ActionView::MissingTemplate (Missing template perfdashboard/contexts/bullet with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby]}. Searched in:
  * "/Users/jimmy/Temp/perfdashboard/spec/dummy/app/views"
  * "/Users/jimmy/Temp/perfdashboard/app/views"
):
  actionview (4.2.1) lib/action_view/path_set.rb:46:in `find'
  actionview (4.2.1) lib/action_view/lookup_context.rb:121:in `find'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:40:in `determine_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:8:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/jimmy/.rbenv/versions/2.1.6/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  /Users/jimmy/Temp/perfdashboard/app/controllers/perfdashboard/requests_controller.rb:33:in `index'
```

**Comment by ezr-ondrej** [comment]
I have forgot to add a file... :(
